apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    log_format custom_format '$remote_addr - $remote_user [$time_local] '
      '"$request" $status $body_bytes_sent '
      '"$http_referer" "$http_user_agent" '
      '$upstream_response_time';
    server {
      access_log /var/log/nginx/access.log custom_format;
      location /nginx_status {
          stub_status on;
          access_log off;
          allow 127.0.0.1; # allow access only from localhost
          deny all; # deny access to everyone else
      }
    }