pipeline {
    agent { label "label" }

    stages {
        stage('Execute hello world script') {
            steps {
                sh 'python3 lesson8/src/hello.py'
            }
        }
    }
}
